name: Create Development Builds

jobs:
  android_device_development_build:
    environment: development
    name: Build Android Device (development)
    params:
      platform: android
      profile: development
    type: build

  ios_device_development_build:
    environment: development
    name: Build iOS Device (development)
    params:
      platform: ios
      profile: development
    type: build

  ios_simulator_development_build:
    environment: development
    name: Build iOS Simulator (development)
    params:
      platform: ios
      profile: development-simulator
    type: build
